In [10]:
import numpy as np 

list_a = [1,2,3,4]
vector_a = np.array([1,2,3,4])

# print(numpy)
# print()
print(f"List a = {list_a}")
# print(list_a**2)    # maka akan error(gagal)
print(f"Vector a = {vector_a}")
print(f"Vector a pangkat 2 : {vector_a**2}")
print(f"Vector a kali 5 : {vector_a*5}")
print(f"List a kali 2 : {list_a*2}")

List a = [1, 2, 3, 4]
Vector a = [1 2 3 4]
Vector a pangkat 2 : [ 1  4  9 16]
Vector a kali 5 : [ 5 10 15 20]
Liat a kali 2 : [1, 2, 3, 4, 1, 2, 3, 4]


In [15]:
matrix_b = np.array([(1,2),(3,4)])
print(f"Matriks b : \n{matrix_b}\n")
print(f"Matriks b^2 : \n{matrix_b**2}")

Matriks b : 
[[1 2]
 [3 4]]

Matriks b^2 : 
[[ 1  4]
 [ 9 16]]


In [17]:
## Matrix kosong/0
zeros_c = np.zeros((2,2))  # Berbentuk Tupple
print(f"Zeros c = \n{zeros_c}")

Zeros c = 
[[0. 0.]
 [0. 0.]]


In [18]:
## Matrix satu/1
ones_d = np.ones((2,2))  # Berbentuk Tupple
print(f"Ones d = \n{ones_d}")

Ones d = 
[[1. 1.]
 [1. 1.]]


In [20]:
jumlah = matrix_b + matrix_b**2 + ones_d
print(f"Jumlah = \n{jumlah}")

Jumlah = 
[[ 3.  7.]
 [13. 21.]]


ModuleNotFoundError: No module named 'pygame'